name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Substitua pelo nome do branch principal do seu repositório, se necessário.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar GitHub Pages
      - name: Configure GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.USER_GITHUB_TOKEN }}
          publish_dir: docs
